# Generated by Django 4.1.4 on 2023-01-17 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('usn', models.OneToOneField(db_column='usn', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='studentapp.student')),
                ('subcode', models.CharField(max_length=10)),
                ('subname', models.CharField(blank=True, max_length=30, null=True)),
                ('attendencepercent', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'attendence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('mid', models.IntegerField(primary_key=True, serialize=False)),
                ('totalmarks', models.IntegerField(blank=True, null=True)),
                ('obtmarks', models.IntegerField(blank=True, null=True)),
                ('sgpa', models.FloatField(blank=True, null=True)),
                ('backlogs', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'marks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Studentloginrel',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='studentapp.authuser')),
            ],
            options={
                'db_table': 'studentloginrel',
                'managed': False,
            },
        ),
    ]
